export const colorOptions = [
  { value: "Black", label: "Black" },
  { value: "Blue", label: "Blue" },
  { value: "Red", label: "Red" },
  { value: "White", label: "White" },
  { value: "Gray", label: "Gray" },
  { value: "Silver", label: "Silver" },
  { value: "Green", label: "Green" },
  { value: "Yellow", label: "Yellow" },
  { value: "Brown", label: "Brown" },
  { value: "Purple", label: "Purple" },
  { value: "Pink", label: "Pink" },
  { value: "Orange", label: "Orange" },
].sort((a, b) => a.label.localeCompare(b.label));

export const brandMotorCycleOptions = [
  { value: "Bajaj", label: "Bajaj" },
  { value: "Kawasaki", label: "Kawasaki" },
  { value: "Honda", label: "Honda" },
  { value: "Yamaha", label: "Yamaha" },
  { value: "Suzuki", label: "Suzuki" },
].sort((a, b) => a.label.localeCompare(b.label));

export const associationOptions = [
  { value: "N/A", label: "N/A" },
  { value: "ABCD association", label: "ABCD association" },
].sort((a, b) => a.label.localeCompare(b.label));

export const routes = [
  {
    zone: 1,
    route: "Poblacion 1 to 5 Barangays and vice-versa",
    adult: 12.0,
    student: 9.6,
    sp: 9.6,
  },
  {
    zone: 2,
    route: "Poblacion to Barangay Hubang and vice versa",
    adult: 14.5,
    student: 11.6,
    sp: 11.6,
  },
  {
    zone: 3,
    route:
      "Poblacion to Barangay Hubang going to Supreme/Boundary and vice versa",
    adult: 17.0,
    student: 13.6,
    sp: 13.6,
  },
  {
    zone: 4,
    route: "Poblacion to Barangay Pisaan and vice-versa",
    adult: 19.0,
    student: 15.6,
    sp: 15.6,
  },
  {
    zone: 5,
    route: "Poblacion to Barangay Pisaan going to Damilag and vice-versa",
    adult: 27.0,
    student: 21.6,
    sp: 21.6,
  },
  {
    zone: 6,
    route: "Poblacion to Barangay Karaos and vice-versa",
    adult: 14.5,
    student: 11.6,
    sp: 11.6,
  },
  {
    zone: 7,
    route: "Poblacion to Barangay Karaos going to Lapag and vice-versa",
    adult: 19.5,
    student: 15.6,
    sp: 15.6,
  },
  {
    zone: 8,
    route: "Poblacion to Barangay San Isidro and vice-versa",
    adult: 17.0,
    student: 13.6,
    sp: 13.6,
  },
  {
    zone: 9,
    route: "Poblacion to Sitio Taglikid/Tropical Heights and vice-versa",
    adult: 22.0,
    student: 17.6,
    sp: 17.6,
  },
  {
    zone: 10,
    route: "Poblacion to Barangay Bayugan 2 and vice-versa",
    adult: 24.5,
    student: 19.6,
    sp: 19.6,
  },
  {
    zone: 11,
    route: "Poblacion to Barangay Lapinigan and vice-versa",
    adult: 32.0,
    student: 25.6,
    sp: 25.6,
  },
  {
    zone: 12,
    route: "Poblacion to Barangay Lapinigan (Alang-alang) and vice-versa",
    adult: 39.5,
    student: 31.6,
    sp: 31.6,
  },
  {
    zone: 13,
    route: "Poblacion to Barangay Pasta and vice-versa",
    adult: 37.0,
    student: 29.6,
    sp: 29.6,
  },
  {
    zone: 14,
    route:
      "Poblacion to Barangay Alegria going to Iglesio ni Cristo) and vice-versa",
    adult: 19.5,
    student: 15.6,
    sp: 15.6,
  },
  {
    zone: 15,
    route: "Poblacion to Barangay Alegria and vice-versa",
    adult: 14.5,
    student: 11.6,
    sp: 11.6,
  },
  {
    zone: 16,
    route: "Poblacion to Barangay Campbagang and vice-versa",
    adult: 22.0,
    student: 17.6,
    sp: 17.6,
  },
  {
    zone: 17,
    route: "Poblacion to Barangay Sta. Ana and vice-versa",
    adult: 19.5,
    student: 15.6,
    sp: 15.6,
  },
  {
    zone: 18,
    route: "Poblacion to Barangay Tagapua and vice-versa",
    adult: 37.0,
    student: 29.6,
    sp: 29.6,
  },
  {
    zone: 19,
    route: "Poblacion to Barangay Borbon and vice-versa",
    adult: 44.5,
    student: 35.6,
    sp: 35.6,
  },
  {
    zone: 20,
    route: "Poblacion to Barangay Rizal and vice-versa",
    adult: 55.0,
    student: 41.6,
    sp: 41.6,
  },
  {
    zone: 21,
    route:
      "Poblacion to Barangay Lucac (starting from Adlayan bridge) and vice-versa",
    adult: 27.0,
    student: 21.6,
    sp: 21.6,
  },
  {
    zone: 22,
    route: "Poblacion to Barangay Bitan-agan and vice-versa",
    adult: 22.0,
    student: 17.6,
    sp: 17.6,
  },
  {
    zone: 23,
    route: "Poblacion to Barangay Das-agan and vice-versa",
    adult: 32.0,
    student: 25.6,
    sp: 25.6,
  },
  {
    zone: 24,
    route: "Poblacion to Barangay Buenasuerte and vice-versa",
    adult: 49.5,
    student: 39.6,
    sp: 39.6,
  },
  {
    zone: 25,
    route: "Poblacion to Barangay Caimpugan and vice-versa",
    adult: 59.5,
    student: 47.6,
    sp: 47.6,
  },
];

export const bloodTypeOptions = [
  { value: "A+", label: "A+" },
  { value: "A-", label: "A-" },
  { value: "B+", label: "B+" },
  { value: "B-", label: "B-" },
  { value: "O+", label: "O+" },
  { value: "O-", label: "O-" },
  { value: "AB+", label: "AB+" },
  { value: "AB-", label: "AB-" },
];

export const insuranceOptions = [
  {
    id: 1,
    name: "Pioneer Insurance & Surety Corporation (Pioneer Intercontinental Inc. Company)",
  },
  { id: 2, name: "Malayan Insurance Company, Inc." },
  { id: 3, name: "BPI/MS Insurance Corporation" },
  { id: 4, name: "AIG Phil. Ins. Company (formerly Chartis Phils., Inc.)" },
  {
    id: 5,
    name: "Bethel General Insurance and Surety Corporation (formerly BF General Insurance Company)",
  },
  { id: 6, name: "Philippines’ First Insurance Co., Inc." },
  { id: 7, name: "Cibeles Insurance Corporation" },
  {
    id: 8,
    name: "Charter Ping An (Phil Charter Ins. Corp or CPAIC) now merged with AXA Philippines",
  },
  {
    id: 9,
    name: "Cocogen Insurance, Inc. (formerly UCPB General Insurance Company)",
  },
  { id: 10, name: "Standard Insurance Company, Inc." },
  { id: 11, name: "Alliedbankers Insurance Corporation" },
  { id: 12, name: "Starr International Insurance, Phils. Branch" },
  {
    id: 13,
    name: "Etiqa Philippines (formerly AsianLife & General Assurance Corporation)",
  },
  {
    id: 14,
    name: "AIA Philippines (formerly Philam Life and Gen. Insurance Company)",
  },
  { id: 15, name: "Prudential Guarantee and Assurance Inc." },
  { id: 16, name: "Bankers Assurance (Malayan Zurich)" },
  { id: 17, name: "First Nationwide Assurance Corporation" },
  {
    id: 18,
    name: "Pacific Cross (formerly Blue Cross Insurance, Inc. and State Bonding and Insurance Company, Inc)",
  },
  { id: 19, name: "Perla Compania de Seguros, Inc." },
  { id: 20, name: "QBE Seabord Insurance Phils, Inc." },
  { id: 21, name: "Stronghold Insurance Company, Inc." },
  { id: 22, name: "Commonwealth Insurance Company" },
  { id: 23, name: "Asia Insurance Corp." },
  { id: 24, name: "Insurance Company of North America" },
  { id: 25, name: "Pioneer Asia Insurance Corporation" },
  { id: 26, name: "Plaridel Surety & Insurance Company" },
  { id: 27, name: "Reliance Surety & Insurance Company" },
  { id: 28, name: "United Insurance Company, Inc." },
  { id: 29, name: "Sterling Insurance Company" },
  { id: 30, name: "Corporate Guarantee and Insurance Company, Inc." },
  { id: 31, name: "People’s General Insurance Corporation" },
  { id: 32, name: "Federal Phoenix Assurance Company, Inc." },
  { id: 33, name: "MAA General Assurance Philippines, Inc." },
  { id: 34, name: "Petrogen Insurance Corporation" },
  { id: 35, name: "Alpha Insurance and Surety Company, Inc." },
  { id: 36, name: "Liberty Insurance Corporation" },
  { id: 37, name: "FPG Insurance Co., Inc" },
  { id: 38, name: "Centennial Guarantee Assurance Corporation" },
  { id: 39, name: "PGA Sompo Japan Insurance, Inc." },
  { id: 40, name: "Mercantile Insurance Company, Inc." },
  { id: 41, name: "Philippine British Assurance Company, Inc." },
  { id: 42, name: "Pacific Union Insurance Company" },
  {
    id: 43,
    name: "SGI Philippines General Insurance Company, Inc. (formerly Monarch Insurance Company, Inc.)",
  },
  { id: 44, name: "Paramount Life and Gen. Ins. Corp." },
  { id: 45, name: "Investors Assurance Corporation" },
  { id: 46, name: "Western Guaranty Corporation" },
  { id: 47, name: "Visayan Surety & Insurance Corporation" },
  { id: 48, name: "Fortune General Insurance Corporation" },
  { id: 49, name: "Intra Strata Assurance Corporation" },
  { id: 50, name: "New India Assurance Company, Ltd" },
  {
    id: 51,
    name: "OONA Insular Insurance Corporation (formerly MAPFRE Insular Insurance Corporation)",
  },
  { id: 52, name: "Country Bankers Insurance Corporation" },
  { id: 53, name: "AFP General Insurance Corporation" },
  { id: 54, name: "Premier Insurance and Surety Corporation" },
  {
    id: 55,
    name: "M Pioneer Insurance Inc. (Previously Republic Surety and Insurance Company, Inc.)",
  },
  { id: 56, name: "Milestone Guaranty and Assurance Corporation" },
  { id: 57, name: "Oriental Assurance Corporation" },
  { id: 58, name: "R&B Insurance Corporation" },
  { id: 59, name: "Asia United Insurance, Inc" },
  { id: 60, name: "Solid Guaranty Inc" },
  { id: 61, name: "Travellers Insurance & Surety Corporation" },
  { id: 62, name: "Metropolitan Insurance Company" },
  { id: 63, name: "Northwest Insurance & Surety Company, Inc" },
  { id: 64, name: "PNB General Insurers Company, Inc." },
  { id: 65, name: "CLIMBS Life and General Inc." },
].map((option) => ({
  value: option.id,
  label: option.name,
}));

export const documentDesc = [
  {
    number: 1,
    description: "Barangay Clearance",
  },
  {
    number: 2,
    description: "Barangay Certification",
  },
  {
    number: 3,
    description: "Picture of Side Car",
  },
  {
    number: 4,
    description: "Insurance TPL/PL",
  },
  {
    number: 5,
    description: "Xerox Copy Driver’s License",
  },
  {
    number: 6,
    description: "Stencil",
  },
  {
    number: 7,
    description: "MTOP Official Receipt",
  },
  {
    number: 8,
    description: "OR /CR Xerox Copy",
  },
  {
    number: 9,
    description: "Police Clearance",
  },
  {
    number: 10,
    description: "Medical Certificate (RHU)",
  },
  {
    number: 11,
    description: "Voter’s ID/ Voter’s Certificate",
  },
  {
    number: 12,
    description: "Certification of Road Worthiness  Inspection Form",
  },
  {
    number: 13,
    description: "Proof of Purchase of Side Card",
  },
];
