export const colorOptions = [
  { value: "Black", label: "Black" },
  { value: "Blue", label: "Blue" },
  { value: "Red", label: "Red" },
  { value: "White", label: "White" },
  { value: "Gray", label: "Gray" },
  { value: "Silver", label: "Silver" },
  { value: "Green", label: "Green" },
  { value: "Yellow", label: "Yellow" },
  { value: "Brown", label: "Brown" },
  { value: "Purple", label: "Purple" },
  { value: "Pink", label: "Pink" },
  { value: "Orange", label: "Orange" },
].sort((a, b) => a.label.localeCompare(b.label));

export const brandMotorCycleOptions = [
  { value: "Bajaj", label: "Bajaj" },
  { value: "Kawasaki", label: "Kawasaki" },
  { value: "Honda", label: "Honda" },
  { value: "Yamaha", label: "Yamaha" },
  { value: "Suzuki", label: "Suzuki" },
].sort((a, b) => a.label.localeCompare(b.label));

export const associationOptions = [
  { value: "N/A", label: "N/A" },
  { value: "ABCD association", label: "ABCD association" },
].sort((a, b) => a.label.localeCompare(b.label));

export const routes = [
  {
    zone: 1,
    route: "Poblacion 1 to 5 Barangays and vice-versa",
    adult: 12.0,
    student: 9.6,
    sp: 9.6,
  },
  {
    zone: 2,
    route: "Poblacion to Barangay Hubang and vice versa",
    adult: 14.5,
    student: 11.6,
    sp: 11.6,
  },
  {
    zone: 3,
    route:
      "Poblacion to Barangay Hubang going to Supreme/Boundary and vice versa",
    adult: 17.0,
    student: 13.6,
    sp: 13.6,
  },
  {
    zone: 4,
    route: "Poblacion to Barangay Pisaan and vice-versa",
    adult: 19.0,
    student: 15.6,
    sp: 15.6,
  },
  {
    zone: 5,
    route: "Poblacion to Barangay Pisaan going to Damilag and vice-versa",
    adult: 27.0,
    student: 21.6,
    sp: 21.6,
  },
  {
    zone: 6,
    route: "Poblacion to Barangay Karaos and vice-versa",
    adult: 14.5,
    student: 11.6,
    sp: 11.6,
  },
  {
    zone: 7,
    route: "Poblacion to Barangay Karaos going to Lapag and vice-versa",
    adult: 19.5,
    student: 15.6,
    sp: 15.6,
  },
  {
    zone: 8,
    route: "Poblacion to Barangay San Isidro and vice-versa",
    adult: 17.0,
    student: 13.6,
    sp: 13.6,
  },
  {
    zone: 9,
    route: "Poblacion to Sitio Taglikid/Tropical Heights and vice-versa",
    adult: 22.0,
    student: 17.6,
    sp: 17.6,
  },
  {
    zone: 10,
    route: "Poblacion to Barangay Bayugan 2 and vice-versa",
    adult: 24.5,
    student: 19.6,
    sp: 19.6,
  },
  {
    zone: 11,
    route: "Poblacion to Barangay Lapinigan and vice-versa",
    adult: 32.0,
    student: 25.6,
    sp: 25.6,
  },
  {
    zone: 12,
    route: "Poblacion to Barangay Lapinigan (Alang-alang) and vice-versa",
    adult: 39.5,
    student: 31.6,
    sp: 31.6,
  },
  {
    zone: 13,
    route: "Poblacion to Barangay Pasta and vice-versa",
    adult: 37.0,
    student: 29.6,
    sp: 29.6,
  },
  {
    zone: 14,
    route:
      "Poblacion to Barangay Alegria going to Iglesio ni Cristo) and vice-versa",
    adult: 19.5,
    student: 15.6,
    sp: 15.6,
  },
  {
    zone: 15,
    route: "Poblacion to Barangay Alegria and vice-versa",
    adult: 14.5,
    student: 11.6,
    sp: 11.6,
  },
  {
    zone: 16,
    route: "Poblacion to Barangay Campbagang and vice-versa",
    adult: 22.0,
    student: 17.6,
    sp: 17.6,
  },
  {
    zone: 17,
    route: "Poblacion to Barangay Sta. Ana and vice-versa",
    adult: 19.5,
    student: 15.6,
    sp: 15.6,
  },
  {
    zone: 18,
    route: "Poblacion to Barangay Tagapua and vice-versa",
    adult: 37.0,
    student: 29.6,
    sp: 29.6,
  },
  {
    zone: 19,
    route: "Poblacion to Barangay Borbon and vice-versa",
    adult: 44.5,
    student: 35.6,
    sp: 35.6,
  },
  {
    zone: 20,
    route: "Poblacion to Barangay Rizal and vice-versa",
    adult: 55.0,
    student: 41.6,
    sp: 41.6,
  },
  {
    zone: 21,
    route:
      "Poblacion to Barangay Lucac (starting from Adlayan bridge) and vice-versa",
    adult: 27.0,
    student: 21.6,
    sp: 21.6,
  },
  {
    zone: 22,
    route: "Poblacion to Barangay Bitan-agan and vice-versa",
    adult: 22.0,
    student: 17.6,
    sp: 17.6,
  },
  {
    zone: 23,
    route: "Poblacion to Barangay Das-agan and vice-versa",
    adult: 32.0,
    student: 25.6,
    sp: 25.6,
  },
  {
    zone: 24,
    route: "Poblacion to Barangay Buenasuerte and vice-versa",
    adult: 49.5,
    student: 39.6,
    sp: 39.6,
  },
  {
    zone: 25,
    route: "Poblacion to Barangay Caimpugan and vice-versa",
    adult: 59.5,
    student: 47.6,
    sp: 47.6,
  },
];

export const bloodTypeOptions = [
  { value: "A+", label: "A+" },
  { value: "A-", label: "A-" },
  { value: "B+", label: "B+" },
  { value: "B-", label: "B-" },
  { value: "O+", label: "O+" },
  { value: "O-", label: "O-" },
  { value: "AB+", label: "AB+" },
  { value: "AB-", label: "AB-" },
];
