create table public."Applications" (
    id bigint generated by default as identity,
    application_date timestamp with time zone null,
    franchise_num text null,
    franchise_status text null,
    operator_id bigint null,
    driver_id bigint null,
    insurance_company smallint null,
    insurance_coc_num text null,
    insurance_expiry_date date null,
    provisional_expiry_date date null,
    body_num text null,
    zone smallint null,
    status text not null default 'pending' :: text,
    constraint ApplicationApproval_pkey primary key (id),
    constraint Applications_body_num_key unique (body_num),
    constraint Applications_driver_id_fkey foreign key (driver_id) references "DriverProfiles" (id) on update cascade on delete cascade,
    constraint Applications_operator_id_fkey foreign key (operator_id) references "OperatorProfiles" (id) on update cascade on delete cascade
) tablespace pg_default;