create table public."OperatorProfiles" (
    id bigint generated by default as identity,
    last_name text null,
    first_name text null,
    middle_name text null,
    extension_name character varying null,
    birth_date date null,
    address text null,
    civil_status text null,
    is_active boolean null,
    contact_num text null,
    date_registered timestamp with time zone null,
    face_photo text null,
    signature_photo text null,
    constraint operatorprofiles_pkey primary key (id)
) tablespace pg_default;