create table public."Payments" (
    id bigint generated by default as identity,
    or_num text null,
    or_date date null,
    amount text null,
    receipt text null,
    created_at timestamp with time zone not null default now(),
    application_id bigint null,
    constraint Payment_pkey primary key (id),
    constraint Payments_application_id_fkey foreign key (application_id) references "Applications" (id) on update cascade on delete cascade
) tablespace pg_default;