create table public."ReportViolations" (
    id bigint generated by default as identity,
    body_num text not null,
    complain text not null,
    date date not null,
    time time without time zone not null,
    violation text null,
    action_taken text not null default 'pending' :: text,
    passenger_id uuid null,
    complainant_name text null,
    complainant_contact_num text null,
    route text null,
    enforcer_id uuid null,
    note text null,
    constraint reportviolations_pkey primary key (id),
    constraint public_ReportViolations_enforcer_id_fkey foreign key (enforcer_id) references "UserLists" (id) on update cascade on delete cascade,
    constraint public_ReportViolations_passenger_id_fkey foreign key (passenger_id) references "UserLists" (id) on update cascade on delete cascade,
    constraint reportviolations_body_num_fkey foreign key (body_num) references "Applications" (body_num) on update cascade on delete cascade
) tablespace pg_default;